volumes:
  n8n_storage:

networks:
  demo_euskal:

x-n8n: &service-n8n
  image: n8nio/n8n:latest
  networks: ['demo_euskal']
  environment:
    - N8N_DIAGNOSTICS_ENABLED=false
    - N8N_PERSONALIZATION_ENABLED=false
    - N8N_ENCRYPTION_KEY
    - N8N_USER_MANAGEMENT_JWT_SECRET
  env_file:
    - .env_euskal


services:

  n8n-import:
    <<: *service-n8n
    hostname: n8n-import
    container_name: n8n-import
    entrypoint: /bin/sh
    command:
      - "-c"
      - "n8n import:credentials --separate --input=/demo-data/credentials && n8n import:workflow --separate --input=/demo-data/workflows"
    volumes:
      - ./n8n/demo-data:/demo-data

  n8n:
    build:
      context: ./n8n
      dockerfile: n8n.dockerfile
    image: custom-n8n:latest
    hostname: n8n
    container_name: n8n
    restart: unless-stopped
    ports:
      - 5678:5678
      - 8000:8000
    volumes:
      - n8n_storage:/home/node/.n8n
      - ./n8n/demo-data:/demo-data
      - ./shared:/data/shared
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      n8n-import:
        condition: service_completed_successfully
    environment:
      - N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE=true
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      - N8N_SECURE_COOKIE=false

  maigret:
    image: soxoj/maigret
    container_name: maigret
    #entrypoint: ["tail", "-f", "/dev/null"]

  sherlock:
    image: sherlock/sherlock
    container_name: sherlock
    #entrypoint: ["tail", "-f", "/dev/null"]
